//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Controller.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_ControllerTYPE              130
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define ID_VIEW_MEDIAFILES              153
#define ID_VIEW_COMPONENT               154
#define ID_VIEW_LAYOUTPROPERTIES        155
#define ID_VIEW_LAYOUTTEMPLATES         156
#define ID_VIEW_CLIENTFILTER            157
#define ID_VIEW_CLIENTINFO              158
#define ID_VIEW_CLIENTLIST              159
#define ID_VIEW_GROUPINFO               160
#define ID_VIEW_GROUPLIST               161
#define ID_VIEW_CLIENTINFOMONITOR       162
#define ID_VIEW_CLIENTSTATELIST         163
#define ID_VIEW_USERLIST                164
#define ID_VIEW_USEREDITOR              165
#define ID_VIEW_LOGLIST                 166
#define ID_VIEW_LOGSEARCH               167
#define ID_VIEW_CALENDER                168
#define ID_VIEW_LAYOUTFILTER            169
#define ID_VIEW_LAYOUTLISTVIEW          170
#define ID_VIEW_SCHEDULEITEM            171
#define ID_VIEW_LAYOUTDESIGNER          172
#define ID_DESIGNEVIEW                  173
#define ID_DESIGNER                     174
#define ID_SCHEDULER                    175
#define ID_CLIENTMANAGE                 176
#define ID_CLIENTMONITOR                177
#define ID_USERMANAGE                   178
#define ID_LOGVIEW                      179
#define ID_SCHEDULER_WND                180
#define ID_SCHEDULER_VIEW               181
#define ID_VIEW_MEDIAFILESLIST          182
#define IDC_MEDIAFILESLIST              183
#define IDC_MEDIAFILESTREE              184
#define IDC_COMPONENTLIST               185
#define ID_REPORTVIEW                   186
#define ID_VIEW_OUTLOOKBAR              187
#define ID_REPORT_CLIENT_STATUS         188
#define ID_REPORT_CLIENT_DOWNLOAD       189
#define ID_REPORT_CLIENT_PLAY           190
#define ID_REPORT_CLIENT_PLAY_SUM       191
#define ID_REPORT_CLIENT_DETAILS        192
#define ID_REPORT_CLIENT_AVAILABILITY   193
#define ID_REPORT_CLIENT_ONLINE_RATES   194
#define ID_VIEW_REPORT_LIST             195
#define ID_VIEW_REPORT_SEARCH_PANE      196
#define ID_ALARMVIEW                    197
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDD_DESIGNER_GRID               310
#define IDD_CLIENT_FILTER               311
#define IDW_LIST_GROUP                  311
#define IDD_CLIENT_EDITOR               312
#define IDW_LIST_CLIENT                 312
#define IDD_DIALOG1                     313
#define IDD_GROUP_INFO                  313
#define IDW_LIST_LOG                    313
#define IDW_LIST_CLIENT_STATUS          314
#define IDD_CLIENT_INFO                 314
#define IDD_LAYOUT_FILTER               315
#define IDW_LIST_USER                   315
#define IDD_SCHEDULE_ITEM               316
#define ID_PROPERTY_CTRL                316
#define IDB_LARGEICONS                  317
#define IDW_LIST_CLIENT_TAB             317
#define ID_LAYOUT_LIST_LARGEICONS       320
#define IDD_LOG_FILTER                  320
#define ID_LAYOUT_LIST_SMALLICONS       321
#define IDD_USER_EDITOR                 321
#define ID_LAYOUT_LIST_ROWDETAILS       322
#define IDD_LOGIN                       322
#define ID_LAYOUT_LIST_STATEICONS       323
#define IDD_HORIZONTALLYCOPY            323
#define ID_LAYOUT_LIST_CLIENTWIDTHSEL   324
#define IDD_VERTICALLYCOPY              324
#define IDC_SCHEDULER_CALENDAR          325
#define IDD_DIALOG2                     325
#define IDD_CONTINUOUS_DEL              325
#define IDC_SCHEDULER_LAYOUTS_BAR       326
#define IDD_SET_PASSWORD                326
#define IDC_SCHEDULER_FILETREE          327
#define IDD_PROPERTY_LAYOUT             328
#define IDD_PROPERTY_LAYER              329
#define IDD_PROPERTY_BASIC_CONTENT      331
#define IDD_PROPERTY_TRANSITION         333
#define IDW_LIST_LAYOUT                 333
#define IDW_LIST_LAYOUT_LIST            333
#define IDD_PROPERTY_MESSAGE            334
#define IDW_LIST_TIMETABLE              334
#define ID_VIEW_LAYOUT_INFO             334
#define ID_LAYOUTMANAGE                 335
#define ID_VIEW_LAYOUT_CATEGORY         335
#define IDD_TEMPLATE                    337
#define ID_RIBBON_BTN_DESIGNER_BINDLAY  337
#define IDD_SCHEDULES                   338
#define ID_RIBBON_BTN_DESIGNER_SAME_INTERVAL1 338
#define IDD_DIALOG3                     339
#define IDD_PROPERTY_PLUGIN             339
#define ID_RIBBON_BTN_DESIGNER_SAME_INTERVAL2 339
#define ID_RIBBON_BTN_DESIGNER_FILL_LAYOUT 340
#define IDD_DIALOG4                     344
#define IDD_PROPERTY_SIMPLE_PLUGIN      344
#define IDD_NEW_USER                    345
#define IDD_DIALOG5                     347
#define IDD_ADD_GROUP                   348
#define IDD_DIALOG6                     349
#define IDD_EMERGENCY_MESSAGE           349
#define IDD_LAYOUT_OPEN                 351
#define IDD_CLIENT_MONITOR_CHART        353
#define IDC_CLOSE_PANEL                 354
#define IDD_UPLOAD_LAYOUT               354
#define IDD_DIALOG7                     355
#define IDD_COMMON_SETTING              355
#define IDB_LAYOUT_SMALL                357
#define IDB_LAYOUT_LARGE                358
#define IDB_USERMGR_SMALL               359
#define IDB_USERMGR_LARGE               361
#define IDB_SCHEDULER_SMALL             362
#define IDB_SCHEDULER_LARGE             363
#define IDB_LOG_SMALL                   364
#define IDB_LOG_LARGE                   365
#define IDB_CLIENTMGR_SMALL             366
#define IDB_CLIENTMGR_LARGE             367
#define IDB_CLIENTMONITOR_SMALL         368
#define IDB_BITMAP2                     369
#define IDB_CLIENTMONITOR_LARGE         369
#define IDD_TRANSLUCENTDIALOG           370
#define IDD_LOGIN1                      371
#define IDD_LOGIN_SKIN                  371
#define IDD_LOADING                     372
#define IDB_BITMAP1                     374
#define IDB_LOGIN_BG                    375
#define IDB_PNG2                        376
#define IDB_LOADING                     376
#define IDD_SELECT_CLIENT_SIZE          377
#define IDB_CLIENT_LARGE                379
#define IDB_USER_LARGE                  380
#define IDB_USER_ADMIN_LARGE            380
#define IDB_BITMAP3                     381
#define IDB_GROUP_LARGE                 381
#define IDB_USER_NORMAL_LARGE           383
#define IDB_DESIGNER_LAYER              384
#define IDB_DESIGNER_MESSAGE            385
#define IDI_LAYER                       386
#define IDI_MESSAGE                     387
#define IDB_CLIENT_DISCONNECTED         388
#define IDB_CLIENT_CRITICAL             389
#define IDB_BITMAP6                     390
#define IDB_CLIENT_STATUS_WELL          390
#define IDB_GROUP_EMPTY                 391
#define IDB_GROUP_NEED_ATTENTION        392
#define IDB_BITMAP7                     393
#define IDB_GROUP_STATUS_WELL           393
#define IDD_CLIENT_MONITOR_SETTINGS     394
#define IDD_LOGIN_SKIN1                 395
#define IDD_LOGIN_SETTING               395
#define IDB_LOGIN_SETTING               395
#define IDD_GROUP_EDITOR                396
#define IDD_RENAME_LAYOUT               397
#define IDI_AUDIO                       398
#define IDI_EMPTYCONTENT                399
#define IDR_MENU_PREVIEW                400
#define IDD_LAYOUT_PUBLISH              401
#define IDD_LAYOUT_WARNING              402
#define IDD_FILE_DETAIL                 403
#define IDB_PNG1                        405
#define IDB_NEW_LOADING                 405
#define IDB_CLIENT_NEED_ATTENTION       406
#define IDB_GROUP_CRITICAL              407
#define IDD_LANGUAGE_SETTING            408
#define IDD_TIMETABLE_SELECTED_LAYOUT_INFO 411
#define IDD_TIMETABLE_EDIT              412
#define IDD_MEDIA_LIB_TREE              414
#define IDD_FILTER_TREE                 414
#define IDD_MEDIA_LIB_SEARCH_BAR        415
#define IDD_MEDIA_LIB_INFO              416
#define IDD_UPLOAD_FILE                 417
#define IDB_LAYOUTMANAGE_LARGE          417
#define IDD_FILE_DETAIL_INFO            418
#define IDB_BITMAP5                     418
#define IDB_LAYOUTMANAGE_SMALL          418
#define IDD_GET_TIME                    419
#define IDD_GET_START_INTERVAL          419
#define ID_MEDIALIBRARY                 420
#define IDD_DIALOG8                     420
#define IDD_MEDIA_RENAME_CATEGORYLIST   420
#define ID_VIEW_MEDIALIBRARY_SEARCHBAR  421
#define IDD_REPORT_CLIENT_STATUS        421
#define ID_VIEW_MEDIALIBRARY_INFO       422
#define ID_VIEW_MEDIALIBRARY_LIST       423
#define IDB_OUTLOOK_LARGE               423
#define IDB_OUTLOOK                     423
#define ID_VIEW_MEDIALIBRARY_CATEGORY   424
#define IDB_OUTLOOK_LARGE_HC            424
#define IDB_BITMAP8                     424
#define IDB_OUTLOOK_HC                  424
#define IDW_LIST_MEDIA_TAB              425
#define IDD_REPORT_CLIENT_DOWNLOAD      425
#define IDW_LIST_MEDIA_STATUS           426
#define IDD_REPORT_CLIENT_PLAY          426
#define IDW_LIST_REPORT_TAB             427
#define IDD_DIALOG9                     427
#define IDD_REPORT_CLIENT_PLAY_SUM      427
#define IDW_LIST_REPORT_STATUS          428
#define IDD_REPORT_CLIENT_DETAIL        428
#define IDD_REPORT_CLIENT_AVAIL         429
#define IDD_REPORT_CLIENT_ONLINE        430
#define IDI_ICON8                       440
#define IDB_BITMAP9                     442
#define IDB_BITMAP4                     443
#define IDB_BITMAP10                    444
#define IDB_MEDIALIB_LARGE              444
#define IDB_MEDIALIB_SMALL              445
#define IDD_PRIVILEGE                   446
#define IDD_UPLOAD_LAYOUT_SHORT         447
#define IDB_CATEGORY_CLOSED             448
#define IDB_CATEGORY_OPENED             449
#define IDB_BITMAP13                    450
#define IDB_TIMETABLE_LARGE             451
#define IDB_BITMAP12                    452
#define IDB_TIMETABLE_SMALL             452
#define IDB_ITEMSTATUS_APPROVED         453
#define IDB_ITEMSTATUS_UNAPPROVED       454
#define IDD_REJECT_REASON               455
#define IDB_PNG3                        456
#define IDB_LOADING_STARTER             456
#define IDD_CLIENT_MONITOR_CHART1       456
#define IDD_GROUP_INFO_NEW              457
#define IDD_LAYOUT_PUBLISH_NEW          458
#define IDD_UPLOAD_URL                  459
#define IDB_BITMAP11                    462
#define IDB_MEDIALIB_LARGE_DISABLE      462
#define IDB_DELETE                      463
#define IDB_P                           464
#define IDB_FILTER                      464
#define IDB_NEW                         465
#define IDB_REFRESH                     466
#define IDB_RENAME                      467
#define IDB_SEARCH                      468
#define IDD_DIALOG10                    469
#define IDD_SEARCH_FILE_MEDIA           469
#define IDD_DIALOG11                    470
#define IDD_REMOVEABLE_STORAGE          470
#define IDD_SEARCH_LAYOUT               471
#define IDD_CLIENT_SEARCH               472
#define IDD_EDIT_GROUP                  473
#define IDR_UNDOREDO                    474
#define IDD_IMPORT_LAYOUT               474
#define IDB_NEW_LOADING_CHINESE         475
#define IDB_LOADING_STARTER_CHINESE     476
#define IDC_AFXBARRES_DELETE_COLUMN     479
#define IDB_AFXBARRES_CLEAR             482
#define IDB_AFXBARRES_CLEAR32           483
#define IDB_AFXBARRES_SEARCH            484
#define IDB_AFXBARRES_SEARCH32          486
#define IDB_BITMAP14                    487
#define IDB_ALARM_MSG                   487
#define IDC_COMBOBOXEX2                 1004
#define IDC_EDIT_X                      1005
#define IDC_CHECK_SHOW                  1006
#define IDC_CHECK2                      1007
#define IDC_CHECK_SNAP                  1007
#define IDC_CHECK_OPERATOR              1007
#define IDC_CHECK_DESIGNER              1007
#define IDC_CHK_MEDIA_FILTER_CREATE     1007
#define IDC_CHECK_SEARCHDLG_DATE        1007
#define IDC_EDIT_Y                      1008
#define IDC_CHK_MEDIA_FILTER_EDIT       1008
#define IDC_BUTTON_SEARCH               1009
#define IDC_CHK_MEDIA_FILTER_DEL        1009
#define IDC_EDIT_NAME                   1010
#define IDC_EDIT_DESC                   1010
#define IDC_CHK_MEDIA_FILTER_LIST       1010
#define IDC_COMBO_GROUP                 1012
#define IDC_STATIC_NAME                 1013
#define IDC_STATIC_DESC                 1013
#define IDC_STATIC_GNAME                1013
#define IDC_STATIC_GROUP                1014
#define IDC_STATIC_CLIENT_FILTER_GROUP  1014
#define IDC_STATIC_CLIENT_FILTER_OWNER  1014
#define IDC_EDIT_LOCATION               1015
#define IDC_STATIC_GROUP2               1015
#define IDC_EDIT_COMPANY                1016
#define IDC_EDIT_ADMIN                  1017
#define IDC_EDIT_CLIENT_INFO_NAME       1018
#define IDC_EDIT_PHONE                  1019
#define IDC_EDIT5                       1020
#define IDC_EDIT_HEIGHT                 1020
#define IDC_EDIT_MAIL                   1021
#define IDC_BUTTON_SAVE                 1022
#define IDC_EDIT_CLIENT_INFO_CONTACT_DESCRIPTION 1022
#define IDC_STATIC_INFO_GROUP           1023
#define IDC_STATIC_INFO                 1024
#define IDC_STATIC_LOCATION             1025
#define IDC_STATIC_COMPANY              1026
#define IDC_STATIC_ADMIN                1027
#define IDC_CHECK_MAMM                  1027
#define IDC_STATIC_PHONE                1028
#define IDC_COMBO_ROTATION              1028
#define IDC_STATIC_MAIL                 1029
#define IDC_LIST_GROUP                  1030
#define IDC_STATIC_MAIL2                1030
#define IDC_STATIC_CLIENT_INFO_CONTACT_DESCRIPTION 1030
#define IDC_EDIT_GNAME                  1031
#define IDC_STATIC_MAIL3                1031
#define IDC_STATIC_CLIENT_INFO_COMPANY  1031
#define IDC_EDIT_CLIENT_INFO_COMPANY    1032
#define IDC_STATIC_MAIL4                1033
#define IDC_STATIC_CLIENT_INFO_REGISTER_USER 1033
#define IDC_STATIC_GDESC                1034
#define IDC_EDIT_CLIENT_INFO_REGISTER_USER 1034
#define IDC_EDIT_GDESC                  1035
#define IDC_STATIC_MAIL5                1035
#define IDC_STATIC_CLIENT_INFO_GROUP    1035
#define IDC_EDIT_CLIENT_INFO_GROUP      1036
#define IDC_STATIC_MAIL6                1037
#define IDC_STATIC_CLIENT_INFO_REGISTER_DATE 1037
#define IDC_EDIT_CLIENT_INFO_REGISTER_DATE 1038
#define IDC_STATIC_CLIENT_INFO_DISPLAY_CARD_TYPE 1039
#define IDC_EDIT_CLIENT_INFO_DISPLAY_CARD_TYPE 1040
#define IDC_DATETIMEPICKER1             1041
#define IDC_DATETIMEPICKER_DURATION     1041
#define IDC_DATETIMEPICKER_START_LOG    1041
#define IDC_STATIC_MAIL8                1041
#define IDC_STATIC_CLIENT_INFO_HARDWARE_INFO 1041
#define IDC_DATETIMEPICKER_START        1042
#define IDC_DATETIMEPICKER_END_LOG      1042
#define IDC_EDIT_CLIENT_INFO_HARDWARE_INFO 1042
#define IDC_DATETIMEPICKER4             1042
#define IDC_DATETIMEPICKER_END          1043
#define IDC_STATIC_MAIL9                1043
#define IDC_STATIC_CLIENT_INFO_SOFTWARE_INFO 1043
#define IDC_DATETIMEPICKER5             1043
#define IDC_STATIC_START_TIME           1044
#define IDC_EDIT_CLIENT_INFO_SOFTWARE_INFO 1044
#define IDC_STATIC_END_TIME             1045
#define IDC_STATIC_LOCATION2            1045
#define IDC_STATIC_CLIENT_INFO_NAME     1045
#define IDC_STATIC_PLAY_DURATION        1046
#define IDC_STATIC_MAIL10               1046
#define IDC_STATIC_CLIENT_INFO_IP_ADDRESS 1046
#define IDC_CHECK_DATE                  1047
#define IDC_EDIT_CLIENT_INFO_IP_ADDRESS 1047
#define IDC_STATIC_MAIL11               1048
#define IDC_STATIC_CLIENT_INFO_BANDWIDTH 1048
#define IDC_COMBO1                      1049
#define IDC_COMBO_OPERATOR              1049
#define IDC_EDIT_MAIL11                 1049
#define IDC_EDIT_CLIENT_INFO_BANDWIDTH  1049
#define IDC_COMBO_LAYOUT                1049
#define IDC_COMBO_TIMETABLE_CATEGORY_EDIT 1049
#define IDC_COMBO_REPORT1_TYPE          1049
#define IDC_COMBO_REPORT2               1049
#define IDC_COMBO_REPORT2_TYPE          1049
#define IDC_URL_HEADER                  1049
#define IDC_COMBO2                      1050
#define IDC_COMBO_ALIGNMENT             1050
#define IDC_COMBO_SEARCHDLG_OWNER       1050
#define IDC_COMBO_SEARCHDLG_LAYOUT_OWNER 1050
#define IDC_COMBO_SEARCH_CLIENT_ADMIN   1050
#define IDC_EDIT_USERNAME               1051
#define IDC_COMBO_SEARCHDLG_WIDTH       1051
#define IDC_EDIT_USERDESC               1052
#define IDC_BUTTON1                     1054
#define IDC_BUTTON_SETPASS              1054
#define IDC_BUTTON_CHOOSE_CLIENT        1054
#define IDC_BUTTON_CONFIGURE            1054
#define IDC_BUTTON_ENTER                1054
#define IDC_UPLOAD_PAUSE                1054
#define IDC_BTN_SAVE                    1054
#define IDC_BTN_SAVE_GROUP_INFO         1054
#define IDC_BTN_SAVE_CLIENT_INFO        1054
#define IDC_BTN_SETTING_LOGIN           1054
#define IDC_BUTTON_NEW_GROUP            1054
#define IDC_BUTTON_DETAIL               1054
#define IDC_BUTTON_LANGUAGE             1054
#define IDC_BUTTON_TIMETABLE_OPEN_CATEGORY 1054
#define IDC_CHECK_ADMIN                 1055
#define IDC_BUTTON3                     1055
#define IDC_BUTTON_DELETE_GROUP         1055
#define IDC_BTN_SAVE_CLIENT_INFO2       1055
#define IDC_BTN_SAVE2                   1055
#define IDC_BTN_SAVE_PRO                1055
#define IDC_CHECK3                      1056
#define IDC_CHECK_SCHEDULER             1056
#define IDC_CHECK_CLIENT                1057
#define IDC_EDIT2                       1059
#define IDC_EDIT_PASSWORD               1059
#define IDC_EDIT_SETPASS_CONFIRM        1059
#define IDC_EDIT_CLIENT_FILTER_LOCATION 1059
#define IDC_EDIT_TIMETABLE_LAYOUT_CATEGORY 1059
#define IDC_NEW_MEDIANAME               1059
#define IDC_EDIT_SEARCH_CLIENT_ADMIN    1059
#define IDC_IDC_SCHGROUP_DESC           1059
#define IDC_SCHGROUP_DESC               1059
#define IDC_DATETIMEPICKER2             1060
#define IDC_SCHEDULE_COPY_START         1061
#define IDC_SCHEDULE_COPY_END           1062
#define IDC_MONDAY                      1063
#define IDC_TUESDAY                     1064
#define IDC_WEDNESDAY                   1065
#define IDC_THURSDAY                    1066
#define IDC_FRIDAY                      1067
#define IDC_SATURDAY                    1068
#define IDC_SUNDAY                      1069
#define IDC_VERTICALLYCOPY_CNT          1070
#define IDC_STATIC_USER_PRIV            1070
#define IDC_VERTICALLYCOPY_HELP         1071
#define IDC_EDIT_SETPASS                1071
#define IDC_EDIT_CLIENT_FILTER_TYPE     1071
#define IDC_MULTIDEL_CNT                1072
#define IDC_EDIT3                       1072
#define IDC_EDIT_NEW_USER_PASSWORD      1072
#define IDC_GROUP_DESC                  1072
#define IDC_EDIT_TIMETABLE_LAYOUT_DURATION_TIME 1072
#define IDC_NEW_URLNAME                 1072
#define IDC_COMBO_TYPE                  1073
#define IDC_EDIT4                       1073
#define IDC_EDIT_NEW_USER_DESCRIPTION   1073
#define IDC_EDIT_TIMETABLE_LAYOUT_LOOPTIMES 1073
#define IDC_CHECK_KEEP_ASPECT_RATIO     1074
#define IDC_EDIT_NEW_USER_PASSWORD2     1074
#define IDC_RADIO_HORIZONTALLY          1075
#define IDC_CHECK_ITALIC                1075
#define IDC_RADIO_VERTICALLY            1076
#define IDC_MFCCOLORBUTTON1             1076
#define IDC_EMGM_COLOR                  1076
#define IDC_CHECK_UNDERLINE             1077
#define IDC_SLIDER_VOLUME               1077
#define IDC_MFCEDITBROWSE_AUDIO         1078
#define IDC_MFCVSLISTBOX_MEDIA          1079
#define IDC_COMBO3                      1083
#define IDC_COMBO_SEARCHDLG_SIZE        1083
#define IDC_COMBO_SEARCHDLG_LAYOUT_SIZE 1083
#define IDC_MFCFONTCOMBO_TEXT           1084
#define IDC_SLIDER_SPEED                1085
#define IDC_EDIT_MESSAGE                1086
#define IDC_SLIDER_TRANS                1086
#define IDC_MFCCOLORBUTTON_TEXT         1087
#define IDC_COMBO_SIZE                  1088
#define IDC_COMBO_DIRECTION             1089
#define IDC_CHECK_BOLD                  1090
#define IDC_STATIC_SPEED                1091
#define IDC_STATIC_SIZE                 1092
#define IDC_STATIC_TITLE                1093
#define IDC_STATIC_SIZE2                1093
#define IDC_STATIC_TEXT                 1093
#define IDC_STATIC_BASIC                1094
#define IDC_STATIC_SIZE3                1094
#define IDC_STATIC_SPEED3               1094
#define IDC_EDIT_LDESC                  1095
#define IDC_STATIC_SPEED2               1095
#define IDC_COMBO_DIRECTION2            1095
#define IDC_COMBO_FONTDIRECTION         1095
#define IDC_EDIT_TAG                    1096
#define IDC_STATIC_SIZE4                1096
#define IDC_EDIT_WIDTH                  1097
#define IDC_STATIC_SIZE5                1097
#define IDC_STATIC_MULTIPLY             1098
#define IDC_STATIC_SIZE6                1098
#define IDC_CHECK_KEEP_ASPACT           1099
#define IDC_STATIC_SIZE7                1099
#define IDC_MFCCOLORBUTTON_BG           1100
#define IDC_CHECK_KEEP_ASPACT2          1100
#define IDC_CHECK_ALIGN2GRID            1100
#define IDC_STATIC_APPEARANCE           1101
#define IDC_STATIC_BG_AUDIO             1102
#define IDC_STATIC_LAYER_LIST           1102
#define IDC_STATIC_SIZECOLOR            1103
#define IDC_STATIC_TRANSITION           1104
#define IDC_STATIC_TYPE                 1105
#define IDC_STATIC_DIRECTION            1106
#define IDC_LIST_TEMPLATE               1107
#define IDC_STATIC_Y                    1108
#define IDC_STATIC_H                    1109
#define IDC_STATIC_X                    1110
#define IDC_STATIC_W                    1111
#define IDC_STATIC_PLAY                 1112
#define IDC_STATIC_W2                   1112
#define IDC_LIST_SCHEDULES              1114
#define IDC_HCOPY_SELECTALL             1115
#define IDC_STATIC_CLIENT_FILTER_TYPE   1116
#define IDC_STATIC_CLIENT_FILTER_NAME   1117
#define IDC_STATIC_CLIENT_FILTER_LOCATION 1118
#define IDC_DATETIMEPICKER_CLIENT_FILTER_REGISTER_DATE 1119
#define IDC_COMBO_OWNER                 1120
#define IDC_EDIT_CLIENT_INFO_DESC       1121
#define IDC_EDIT_CLIENT_INFO_LOCATION   1122
#define IDC_EDIT_CLIENT_INFO_HARDWARE_ID 1123
#define IDC_EDIT_CLIENT_INFO_CONTACT    1124
#define IDC_EDIT_CLIENT_INFO_CONTACT_EMAIL 1125
#define IDC_EDIT_CLIENT_INFO_CONTACT_PHONE 1126
#define IDC_EDIT_CLIENT_FILTER_NAME     1127
#define IDC_EDIT_CLIENT_FILTER_OWNER    1128
#define IDC_STATIC_CLIENT_FILTER_REGISTER_DATE 1129
#define IDC_BUTTON_CLIENT_FILTER_SEARCH 1130
#define IDC_STATIC_CLIENT_INFO_DESCRIPTION 1131
#define IDC_STATIC_CLIENT_INFO_LOCATION 1132
#define IDC_STATIC_CLIENT_INFO_HARDWARE_ID 1133
#define IDC_STATIC_CLIENT_INFO_CONTACT  1134
#define IDC_STATIC_CLIENT_INFO_CONTACT_EMAIL 1135
#define IDC_STATIC_CLIENT_INFO_CONTACT_PHONE 1136
#define IDC_STATIC_CLIENT_INFO_GROUP1   1137
#define IDC_EDIT_NEW_USER_NAME          1140
#define IDC_COMBO_NEW_USER_CHARACTER    1141
#define IDC_COMBO_NEW_USER_CHARACTER1   1141
#define IDC_RADIO1                      1141
#define IDC_RADIO_EDIT_USER_PRIVILAGE   1141
#define IDC_RADIO_LANGUAGE              1141
#define IDC_RADIO_ONE_WEEK              1141
#define IDC_RADIO2                      1142
#define IDC_RADIO3                      1143
#define IDC_GROUP_NAME                  1143
#define IDC_RADIO4                      1144
#define IDC_EMGM_FONT                   1144
#define IDC_EMGM_DATE_PICKER            1146
#define IDC_EMGM_DURATION               1147
#define IDC_EMGM_STARTTIME              1148
#define IDC_EMGM_TEXT                   1149
#define IDC_EDIT_LAYOUT                 1150
#define IDC_LIST_LAYOUT                 1152
#define IDC_BUTTON_OPEN                 1154
#define IDC_BUTTON_RENAME               1155
#define IDC_BUTTON_DELETE               1156
#define IDC_BUTTON_EXIT                 1158
#define IDC_CLIENT_MONITOR_CHART1       1159
#define IDC_CLIENT_MONITOR_CHART2       1160
#define IDC_CLIENT_MONITOR_CHART3       1161
#define IDC_CLIENT_MONITOR_CHART4       1162
#define IDC_CLIENT_MONITOR_CHART5       1163
#define IDC_CLIENT_MONITOR_CHART6       1164
#define IDC_UPLOAD_PROGRESS             1165
#define ID_UPLOAD_START                 1166
#define IDC_DOWNLOAD_CANCEL             1167
#define IDC_UPLOAD_CANCEL               1167
#define IDC_UPLOAD_INFO                 1168
#define IDC_PROGRESS3                   1171
#define IDC_PROGRESS_OPEN_LAYOUT        1171
#define IDC_BUTTON2                     1172
#define IDC_EDIT_GROUP                  1172
#define IDC_BTN_REPORT1_EXPORT          1172
#define IDC_BTN_REPORT2_EXPORT          1172
#define IDC_BTN_REPORT5_EXPORT_TXT      1172
#define IDC_BTN_SETPASS                 1172
#define IDC_BTN_SEARCH                  1172
#define IDC_ROOT_DIR                    1173
#define IDC_STATIC_AUDIOFILE            1174
#define IDC_STATIC_PIXELS_Y             1176
#define IDC_STATIC_PIXELS_W             1177
#define IDC_STATIC_PIXELS_H             1178
#define IDC_LOADING_STR                 1179
#define IDC_LIST_CLIENT_SIZE            1180
#define IDC_REFRESH_DURATION            1183
#define IDC_IPADDRESS1                  1184
#define IDC_STATIC_VERSION              1185
#define IDC_CHECK_ENABLE_AUDIO          1186
#define IDC_SLIDER_TRANSPARENCY         1188
#define IDC_LIST_LAYERS                 1189
#define IDC_SLIDER_VOLUMN               1190
#define IDC_STATIC_VOLUMN               1191
#define IDC_STATIC_VOLUME               1191
#define IDC_STATIC_SERVER_IP            1192
#define IDC_IPADDRESS_SERVER            1193
#define IDC_STATIC_PORT                 1194
#define IDC_PORT                        1195
#define IDC_SERVER_PORT                 1195
#define IDC_FRAME                       1196
#define IDC_STATIC_WEBBROWSER           1197
#define IDC_LIST_MSG_HISTORY            1198
#define IDC_LIST_CLIENT                 1198
#define IDC_LIST_LANGUAGE               1198
#define IDC_STATIC_BROWSER              1199
#define IDC_STATIC_WARNING              1200
#define IDC_MFCEDITBROWSE_PATH          1201
#define IDC_STATIC_PATH                 1202
#define IDC_MFCPROPERTYGRID1            1203
#define IDC_MFCPROPERTYGRID_DETAIL      1203
#define IDC_EDIT_LAYERDURATION          1204
#define IDC_MFCPROPERTYGRID_DETAIL2     1204
#define IDC_CHECK_LOOPSYNC              1205
#define IDC_EDIT_LAYOUT_DURATION        1206
#define IDC_STATIC_LAYER_DURATION       1207
#define IDC_STATIC_LAYOUT_DURATION      1208
#define IDC_SLIDER1                     1209
#define IDC_SLIDER_GROUP_VOLUME         1209
#define IDC_STATIC_TRANSPARENCY         1210
#define IDC_STATIC_CONFIRM_PASSWORD     1211
#define IDC_CATEGORY_DESC               1212
#define IDC_LIST1                       1214
#define IDC_LIST_REPORT1                1214
#define IDC_STATIC_LANGUAGE             1215
#define IDC_STATIC_TIMETABLE_CATEGORY   1218
#define IDC_EDIT_TIMETABLE_LAYOUT_NAME  1221
#define IDC_STATIC_TIMETABLE_LAYOUT_NAME 1222
#define IDC_STATIC_TIMETABLE_LAYOUT_CATEGORY 1223
#define IDC_STATIC_TIMETABLE_LAYOUT_DURATION_TIME 1224
#define IDC_STATIC_TIMETABLE_LAYOUT_LOOPTIMES 1225
#define IDC_EDIT_TIMETABLE_NAME_EDIT    1226
#define IDC_STATIC_TIMETABLE_EDIT_NAME  1227
#define IDC_MEDIALIB_TREE               1229
#define IDC_FILTER_TREE                 1229
#define IDC_MEDIALIB_CATEGORY_NEW       1231
#define IDC_FILTER_CATEGORY_NEW         1231
#define IDC_MEDIALIB_CATEGORY_DEL       1232
#define IDC_FILTER_CATEGORY_DEL         1232
#define IDC_MEDIALIB_CATEGORY_RENAME    1233
#define IDC_FILTER_CATEGORY_RENAME      1233
#define IDC_STATIC_OWNER                1235
#define IDC_STATIC_STARTDATE            1236
#define IDC_STATIC_ENDDATE              1237
#define IDC_STATIC_APPROVAL             1238
#define IDC_MEDIA_INFO_DESC             1239
#define IDC_STATIC_FOREGROUND           1239
#define IDC_TREE1                       1240
#define IDC_STATIC_BACKGROUND           1240
#define IDC_CATEGORY_TREE_NEW           1240
#define IDC_FILTER_CATEGORY_REFRESH     1241
#define IDC_MFCBUTTON1                  1242
#define IDC_FILTER_CATEGORY_FILTER      1242
#define IDC_EDT_START_INTERVAL          1243
#define IDC_GETTIME_STATIC1             1244
#define IDC_EDIT1                       1245
#define IDC_ORIGINAL_MEDIANAME          1245
#define IDC_EDIT_REPORT1_KEYWORD        1245
#define IDC_EDIT_REPORT2_KEYWORD        1245
#define IDC_DETAIL_INFO                 1245
#define IDC_EDIT_FILTER                 1245
#define IDC_USER_DESC                   1245
#define IDC_EDIT_REJECT_REASON          1245
#define IDC_EDIT_SEARCHDLG_DESC         1245
#define IDC_DESC_SEARCHDLG_LAYOUT       1245
#define IDC_EDIT_SEARCHDLG_LAYOUT_DESC  1245
#define IDC_TIMES                       1245
#define IDC_EDIT_SEARCH_CLIENT_NAME     1245
#define IDC_SCHGROUP_NAME               1245
#define IDC_EDIT6                       1246
#define IDC_EDIT_SEARCH_CLIENT_LOCATION 1246
#define IDC_STATIC_START                1247
#define IDC_EDIT7                       1247
#define IDC_EDIT_SEARCH_CLIENT_COMPANY  1247
#define IDC_STATIC_END                  1248
#define IDC_EDIT8                       1248
#define IDC_EDIT_SEARCH_CLIENT_TEL      1248
#define IDC_STATIC_FRAME                1249
#define IDC_EDIT9                       1249
#define IDC_EDIT_SEARCH_CLIENT_EMAIL    1249
#define IDC_EDIT10                      1250
#define IDC_EDIT_SEARCH_CLIENT_IP       1250
#define IDC_EDIT11                      1251
#define IDC_EDIT_SEARCH_CLIENT_HARDWARE 1251
#define IDC_DATETIMEPICKER_REPORT1_START 1252
#define IDC_DATETIMEPICKER_REPORT1_END  1253
#define IDC_BTN_REPORT1_SEARCH          1254
#define IDC_EDIT_REPORT_KEYWORD         1255
#define IDC_DATETIMEPICKER_REPORT2_START 1255
#define IDC_DATETIMEPICKER_REPORT1_END2 1255
#define IDC_DATETIMEPICKER_REPORT_END   1256
#define IDC_DATETIMEPICKER_REPORT2_END  1256
#define IDC_BTN_REPORT_EXPORT_EXL       1257
#define IDC_BTN_REPORT2_SEARCH          1257
#define IDC_COMBO_REPORT_TYPE           1258
#define IDC_TIMETABLE_INFO              1258
#define IDC_STATIC_REPORT1_TYPE         1258
#define IDC_DATETIMEPICKER_REPORT_START 1259
#define IDC_STATIC_REPORT1_KEYWORD      1259
#define IDC_EDIT_REPORT_KEYWORD_DLD     1260
#define IDC_STATIC_REPORT1_START        1260
#define IDC_DATETIMEPICKER_REPORT_START_DLD 1261
#define IDC_STATIC_REPORT1_END          1261
#define IDC_DATETIMEPICKER_REPORT_END_DLD 1262
#define IDC_STATIC_REPORT2_TYPE         1262
#define IDC_STATIC_REPORT7_TYPE2        1262
#define IDC_STATIC_REPORT7_GROUP        1262
#define IDC_COMBO_REPORT_TYPE_DLD       1263
#define IDC_STATIC_REPORT2_START        1263
#define IDC_STATIC_REPORT1_END2         1263
#define IDC_LIST_REPORT_DLD             1264
#define IDC_STATIC_REPORT2_KEYWORD      1264
#define IDC_BTN_REPORT_SEARCH           1265
#define IDC_STATIC_REPORT2_END          1265
#define IDC_LIST_REPORT2                1266
#define IDC_MEDIA_TUMBNAIL              1266
#define IDC_STATIC_REPORT3_TYPE         1266
#define IDC_STATIC_REPORT3_KEYWORD      1267
#define IDC_EDIT_REPORT3_KEYWORD        1268
#define IDC_COMBO_REPORT3_TYPE          1269
#define IDC_STATIC_REPORT3_START        1270
#define IDC_STATIC_REPORT3_END          1271
#define IDC_DATETIMEPICKER_REPORT3_START 1272
#define IDC_DATETIMEPICKER_REPORT3_END  1273
#define IDC_BTN_REPORT3_SEARCH          1274
#define IDC_BTN_REPORT3_EXPORT          1275
#define IDC_LIST_REPORT3                1276
#define IDC_STATIC_REPORT4_TYPE         1277
#define IDC_COMBO_REPORT4_TYPE          1278
#define IDC_EDIT_REPORT4_KEYWORD        1279
#define IDC_STATIC_REPORT4_KEYWORD      1280
#define IDC_STATIC_REPORT4_START        1281
#define IDC_STATIC_REPORT4_END          1282
#define IDC_DATETIMEPICKER_REPORT4_START 1283
#define IDC_DATETIMEPICKER_REPORT4_END  1284
#define IDC_BTN_REPORT4_SEARCH          1285
#define IDC_BTN_REPORT4_EXPORT          1286
#define IDC_LIST_REPORT4                1287
#define IDC_STATIC_REPORT5_TYPE         1288
#define IDC_STATIC_REPORT5_KEYWORD      1289
#define IDC_COMBO_REPORT5_TYPE          1290
#define IDC_EDIT_REPORT5_KEYWORD        1291
#define IDC_BTN_REPORT5_SEARCH          1292
#define IDC_BTN_REPORT5_EXPORT_EXL      1293
#define IDC_LIST_REPORT5                1294
#define IDC_STATIC_REPORT6_TYPE         1295
#define IDC_COMBO_REPORT6_TYPE          1296
#define IDC_STATIC_REPORT6_START        1297
#define IDC_DATETIMEPICKER_REPORT6_START 1298
#define IDC_BTN_REPORT6_SEARCH          1299
#define IDC_BTN_REPORT6_EXPORT          1300
#define IDC_DATETIMEPICKER_REPORT6_END  1301
#define IDC_STATIC_REPORT6_END          1302
#define IDC_EDIT_REPORT6_KEYWORD        1303
#define IDC_STATIC_REPORT6_KEYWORD      1304
#define IDC_LIST_REPORT6                1305
#define IDC_STATIC_REPORT7_TYPE         1306
#define IDC_COMBO_REPORT7_TYPE          1307
#define IDC_STATIC_REPORT7_KEYWORD      1308
#define IDC_EDIT_REPORT7_KEYWORD        1309
#define IDC_STATIC_REPORT7_START        1310
#define IDC_STATIC_REPORT7_END          1311
#define IDC_DATETIMEPICKER_REPORT7_START 1312
#define IDC_DATETIMEPICKER_REPORT7_END  1313
#define IDC_BTN_REPORT7_SEARCH          1314
#define IDC_BTN_REPORT7_EXPORT          1315
#define IDC_LIST_REPORT7                1316
#define IDC_INFORMATION                 1317
#define IDC_CHK_MEDIA_CREATE            1318
#define IDC_CHK_MEDIA_EDIT              1319
#define IDC_STATIC_GROUPVOLUME          1319
#define IDC_CHK_MEDIA_DEL               1320
#define IDC_STATIC_WORKTIME             1320
#define IDC_CHK_MEDIA_GET               1321
#define IDC_DATETIMEPICKER3             1321
#define IDC_DATETIMEPICKER_TO           1321
#define IDC_RDATETIMEPICKER3            1321
#define IDC_REFRESH_DATETIMEPICKER      1321
#define IDC_CHK_LAYOUT_FILTER_CREATE    1322
#define IDC_STATIC_FROM                 1322
#define IDC_CHK_LAYOUT_FILTER_EDIT      1323
#define IDC_STATIC_TO                   1323
#define IDC_CHK_LAYOUT_FILTER_DEL       1324
#define IDC_DATETIMEPICKER_FROM         1324
#define IDC_CHK_LAYOUT_FILTER_LIST      1325
#define IDC_CHECK1                      1325
#define IDC_CHECK_ALWAYS_WORK           1325
#define IDC_CHECK_SEARCHDLG_LAYOUT_DATE 1325
#define IDC_CHK_TIMETABLE_CREATE        1326
#define IDC_MONTHCALENDAR1              1326
#define IDC_CHK_TIMETABLE_EDIT          1327
#define IDC_BTN_EXPORT_EXL              1327
#define IDC_BTN_EXPORT_CSV              1327
#define IDC_CHK_TIMETABLE_DEL           1328
#define IDC_STATIC_PLAYER_GROUP         1328
#define IDC_CHK_TIMETABLE_GET           1329
#define IDC_STATIC_ROTATION             1329
#define IDC_CHK_USER_CREATE             1330
#define IDC_CHK_USER_EDIT               1331
#define IDC_CHK_USER_DEL                1332
#define IDC_CHK_USER_LIST               1333
#define IDC_CHK_CLIENT_CREATE           1334
#define IDC_CHK_CLIENT_EDIT             1335
#define IDC_CHK_CLIENT_DEL              1336
#define IDC_CHK_CLIENT_LIST             1337
#define IDC_CHK_CLIENTGROUP_CREATE      1338
#define IDC_CHK_CLIENTGROUP_EDIT        1339
#define IDC_CHK_CLIENTGROUP_DEL         1340
#define IDC_CHK_CLIENTGROUP_GET         1341
#define IDC_CHK_LAYOUT_CREATE           1342
#define IDC_CHK_LAYOUT_EDIT             1343
#define IDC_GROUP_PRIVILAGE             1343
#define IDC_GROUP_PRIVILAGES            1343
#define IDC_CHK_LAYOUT_DEL              1344
#define IDC_CHK_LAYOUT_GET              1345
#define IDC_GROUP_MEDIA                 1346
#define IDC_CHK_MEDIA_AUDIT             1347
#define IDC_CHK_MEDIA_RETIRE            1348
#define IDC_CHK_TIMETABLE_FILTER_CREATE 1349
#define IDC_CHK_TIMETABLE_FILTER_EDIT   1350
#define IDC_CHK_TIMETABLE_FILTER_DEL    1351
#define IDC_CHK_TIMETABLE_FILTER_LIST   1352
#define IDC_CHK_SCHEDULE_CREATE         1353
#define IDC_CHK_SCHEDULE_EDIT           1354
#define IDC_GROUP_LAYOUT                1354
#define IDC_CHK_SCHEDULE_DEL            1355
#define IDC_CHK_SCHEDULE_GET            1356
#define IDC_CHK_SCHEDULE_FILTER_CREATE  1357
#define IDC_CHK_SCHEDULE_FILTER_EDIT    1358
#define IDC_CHK_SCHEDULE_FILTER_DEL     1359
#define IDC_CHK_SCHEDULE_FILTER_LIST    1360
#define IDC_CHK_LAYOUT_AUDIT            1361
#define IDC_CHK_TIMETABLE_AUDIT         1362
#define IDC_GROUP_TIMETABLE             1363
#define IDC_CHECK51                     1364
#define IDC_GROUP_SCHEDULE              1364
#define IDC_CHK_SCHEDULE_AUDIT          1365
#define IDC_CHK_EM_CREATE               1366
#define IDC_CHK_EM_EDIT                 1367
#define IDC_CHK_EM_DEL                  1368
#define IDC_CHK_EM_GET                  1369
#define IDC_CHK_EM_AUDIT                1370
#define IDC_CHK_PRIVILEGE_EDIT          1371
#define IDC_CHK_REPORT_VIEW             1372
#define IDC_MEDIA_CATEGORY              1373
#define IDC_LAYOUT_CATEGORY             1374
#define IDC_TIMETABLE_CATEGORY          1375
#define IDC_SCHEDULE_CATEGORY           1376
#define IDC_GROUP_EDIT                  1377
#define IDC_GROUP_CLIENT                1378
#define IDC_GROUP_CLIENT_GROUP          1379
#define IDC_GROUP_EMMERGENCY            1380
#define IDC_GROUP_VIEW                  1381
#define IDC_GROUP_PRI                   1382
#define IDC_BTN_REJECT_REASON           1383
#define IDC_GROUP_VIEW2                 1383
#define IDC_GROUP_LOG                   1383
#define IDC_CHK_REPORT_VIEW2            1384
#define IDC_CHK_LOG_VIEW                1384
#define IDC_CHK_REG_CLIENT              1386
#define IDC_CHK_LOGIN_CLIENT            1387
#define IDC_STATIC_CONTENT              1387
#define IDC_GROUP_LOG2                  1388
#define IDC_STATIC_LAYER                1388
#define IDC_CHK_LOGIN_CONTROLLER        1389
#define IDC_STATIC_LAYOUT               1389
#define IDC_BTN_REFRESH_USER            1390
#define IDC_RADIO_ONE_MONTH             1392
#define IDC_RADIO_THREE_MONTH           1393
#define IDC_RADIO_THREE_MONTH2          1394
#define IDC_RADIO_USER_DEFINE           1394
#define IDC_BUTTON4                     1394
#define IDC_BUTTON_CHECKALL             1394
#define IDC_BUTTON_UNCHECKALL           1395
#define IDC_BUTTON_STOP                 1396
#define IDC_COMBO_MEDIATYPE             1399
#define IDC_FILTER_SEARCH               1399
#define IDC_FILTER_CATEGORY_SEARCH      1399
#define IDC_COMBO4                      1400
#define IDC_COMBO_SEARCHDLG_AUDIT       1400
#define IDC_COMBO_SEARCHDLG_LAYOUT_AUDIT 1400
#define IDC_STATIC_HOST                 1400
#define IDC_COMBO_SEARCHDLG_GROUP       1401
#define IDC_REMOVEABLEPATH              1401
#define IDC_DATETIMEPICKER_SEARCHDLG_END 1402
#define IDC_LIST2                       1402
#define IDC_DATETIMEPICKER_SEARCHDLG_START 1403
#define IDC_DURATION                    1403
#define IDC_BUTTON_SEARCHDLG_SEARCH     1404
#define IDC_STATIC_SEARCHDLG_END        1405
#define IDC_STATIC_SEARCHDLG_START      1406
#define IDC_COMBO_SEARCHDLG_LAYOUT_GROUP 1409
#define IDC_STATIC_SEARCHDLG_LAYOUT_START 1410
#define IDC_DATETIMEPICKER_SEARCHDLG_LAYOUT_START 1411
#define IDC_STATIC_SEARCHDLG_LAYOUT_END 1412
#define IDC_DATETIMEPICKER_SEARCHDLG_LAYOUT_END 1413
#define IDOK_LAYOUT_SEARCH              1414
#define IDC_COMBO_SEARCH_CLIENT_GROUP   1415
#define IDC_HOTKEY1                     1416
#define IDC_COMBO_SEARCHDLG_DUR         1417
#define IDC_STATIC_SHUTDOWN             1417
#define IDC_COMBO_SEARCHDLG_TYPE        1418
#define IDC_COMBO_SEARCHDLG_HEIGHT      1419
#define IDC_ACTUAL_RUNTIME              1420
#define IDC_STATIC_PIXELS_X             1421
#define IDC_Y_LABEL                     1422
#define IDC_X_LABEL                     1423
#define IDC_S3LINK                      1425
#define IDC_LOGO                        1426
#define IDC_BUTTON_ADD                  1427
#define IDC_BTN_ADD_ALARMSET            1427
#define IDC_BTN_DELETE                  1428
#define IDC_DATETIMEPICKER_MEDIA_START  4465
#define IDC_DATETIMEPICKER_MEDIA_END    4466
#define IDC_COMBO_APPROVAL              4467
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_SYS_SETTING                  32771
#define ID_SYS_RE_CONNECT               32772
#define ID_RIBBON_BTN_DESIGNER_NEW      32773
#define ID_RIBBON_BTN_DESIGNER_OPEN     32774
#define ID_RIBBON_BTN_DESIGNER_CLOSE    32775
#define ID_RIBBON_BTN_DESIGNER_SAVE     32776
#define ID_RIBBON_BTN_DESIGNER_SAVEAS   32777
#define ID_RIBBON_BTN_DESIGNER_DELETE   32778
#define ID_RIBBON_BTN_DESIGNER_PUBLISH  32779
#define ID_RIBBON_BTN_DESIGNER_EXPORT   32780
#define ID_RIBBON_BTN_DESIGNER_IMPORT   32781
#define ID_RIBBON_BTN_DESIGNER_MRU      32782
#define ID_RIBBON_BTN_DESIGNER_ADDGROUP 32783
#define ID_RIBBON_BTN_DESIGNER_UNDO     32784
#define ID_RIBBON_BTN_DESIGNER_REDO     32785
#define ID_RIBBON_BTN_DESIGNER_DELETEITEM 32786
#define ID_RIBBON_BTN_DESIGNER_COPY     32787
#define ID_RIBBON_BTN_DESIGNER_CUT      32788
#define ID_RIBBON_BTN_DESIGNER_PASTE    32789
#define ID_RIBBON_BTN_DESIGNER_SELECTALL 32790
#define ID_RIBBON_BTN_DESIGNER_PREVIEWWINMODE 32791
#define ID_RIBBON_BTN_SCHEDULE_GO       32792
#define ID_RIBBON_BTN_DESIGNER_REFRESH  32793
#define ID_RIBBON_BTN_CLTMGMT_ADDGROUP  32794
#define ID_RIBBON_BTN_CLTMGMT_DELGROUP  32795
#define ID_RIBBON_BTN_CLTMGMT_EDITSCHEDULE 32796
#define ID_RIBBON_BTN_CLTMGMT_DISABLECLT 32797
#define ID_RIBBON_BTN_CLTMGMT_ENABLECLT 32798
#define ID_RIBBON_BTN_CLTMGMT_DELCLT    32799
#define ID_RIBBON_BTN_CLTMGMT_EDITMSG   32800
#define ID_RIBBON_BTN_CLTMGMT_SAVE      32801
#define ID_RIBBON_BTN_SCHEDULE_SAVE     32802
#define ID_RIBBON_BTN_SCHEDULE_PRINT    32803
#define ID_RIBBON_BTN_SCHEDULE_EXPORT   32804
#define ID_RIBBON_BTN_SCHEDULE_IMPORT   32805
#define ID_RIBBON_BTN_SCHEDULE_COPY     32806
#define ID_RIBBON_BTN_SCHEDULE_PASTE    32807
#define ID_RIBBON_BTN_SCHEDULE_DEL      32808
#define ID_RIBBON_BTN_SCHEDULE_HMULTICOPY 32809
#define ID_RIBBON_BTN_SCHEDULE_VMULTICOPY 32810
#define ID_RIBBON_BTN_SCHEDULE_MULTIDEL 32811
#define ID_RIBBON_BTN_SCHEDULE_SET_DEFAULT 32812
#define ID_RIBBON_BTN_SCHEDULE_ALIGNUP  32813
#define ID_RIBBON_BTN_SCHEDULE_ALIGNDOWN 32814
#define ID_RIBBON_BTN_CLTMNT_REFRESH    32815
#define ID_RIBBON_BTN_USRMGMT_CREATE    32816
#define ID_RIBBON_BTN_USRMGMT_DEL       32817
#define ID_RIBBON_BTN_USRMGMT_SAVE      32818
#define ID_RIBBON_BTN_USRMGMT_EDIT      32819
#define ID_RIBBON_BTN_LOG_PRINT         32820
#define ID_RIBBON_BTN_LOG_REFRESH       32821
#define ID_RIBBON_BTN_SCHEDULE_PREVIEWWINMODE 32822
#define ID_RIBBON_BTN_DESIGNER_MOVETOFRONT 32823
#define ID_RIBBON_BTN_DESIGNER_MOVEFORWARD 32824
#define ID_RIBBON_BTN_DESIGNER_MOVETOBACK 32825
#define ID_RIBBON_BTN_DESIGNER_MOVEBACKWARD 32826
#define ID_RIBBON_COMBOX_SCHEDULE_TIMEDELTA 32827
#define ID_RIBBON_COMBOX_LAYOUT_ZOOM    32828
#define ID_RIBBON_BTN_CLTMGMT_OFFLINESCHEDULE 32829
#define ID_RIBBON_LAYOUT_PROGRESS       32830
#define ID_RIBBON_BTN_LAYOUT_PROGRESS   32831
#define ID_RIBBON_BTN_SCHEDULE_PREVIEW  32832
#define ID_RIBBON_BTN_DESIGNER_PREVIEW  32833
#define ID_RIBBON_BTN_PREVIEW_10X7      32834
#define ID_RIBBON_BTN_PREVIEW_12X10     32835
#define ID_RIBBON_BTN_PREVIEW_19X10     32836
#define ID_RIBBON_BTN_SCHEDULE_REMOVE_DEFAULT 32837
#define IDC_STATIC_SNAP                 32838
#define ID_RIBBON_BTN_MEDIA_PREVIEW     32901
#define ID_RIBBON_BTN_MEDIA_APPROVE     32902
#define ID_RIBBON_BTN_MEDIA_REJECT      32903
#define ID_RIBBON_BTN_MEDIA_REQUEST     32904
#define ID_RIBBON_BTN_MEDIA_UPLOADFILE  32905
#define ID_RIBBON_BTN_MEDIA_CHANGEFILE  32906
#define ID_RIBBON_BTN_MEDIA_SYNCFILE    32907
#define ID_RIBBON_BTN_MEDIA_FORCESYNCFILE 32908
#define ID_RIBBON_BTN_MEDIA_DELFILE     32909
#define ID_RIBBON_BTN_MEDIA_RETIREFILE  32910
#define ID_RIBBON_BTN_MEDIA_ADDWORKSPACE 32911
#define ID_RIBBON_BTN_MEDIA_SYNCWORKSPACE 32912
#define ID_RIBBON_BTN_MEDIA_STARTUPLOAD 32913
#define ID_RIBBON_BTN_MEDIA_PAUSEUPLOAD 32914
#define ID_RIBBON_BTN_MEDIA_CANCELUPLOAD 32915
#define ID_RIBBON_BTN_MEDIA_STARTDOWNLOAD 32916
#define ID_RIBBON_BTN_MEDIA_PAUSEDOWNLOAD 32917
#define ID_RIBBON_BTN_MEDIA_CANCELDOWNLOAD 32918
#define ID_RIBBON_BTN_CLTMGMT_RESTARTCLT 32919
#define ID_RIBBON_BTN_CLTMGMT_SHUTDOWNCLT 32920
#define ID_RIBBON_BTN_CLTMGMT_STARTCLT  32921
#define ID_RIBBON_BTN_CLTMGMT_UPLOADCLT 32922
#define ID_RIBBON_BTN_CLTMGMT_UPDATECLT 32923
#define ID_RIBBON_BTN_MEDIA_UPLOADINGLIST 32924
#define ID_RIBBON_BTN_MEDIA_UPLOADEDLIST 32925
#define ID_RIBBON_BTN_MEDIA_UPLOADFAILLIST 32926
#define ID_RIBBON_BTN_MEDIA_DOWNLOADINGLIST 32927
#define ID_RIBBON_BTN_MEDIA_DOWNLOADEDLIST 32928
#define ID_RIBBON_BTN_MEDIA_DOWNLOADFAILLIST 32929
#define ID_RIBBON_BTN_MEDIA_RENAME_CATE 32930
#define ID_RIBBON_BTN_TIMETABLE_CREATE  32940
#define ID_RIBBON_BTN_TIMETABLE_CLOSE   32941
#define ID_RIBBON_BTN_TIMETABLE_PUBLISH 32942
#define ID_RIBBON_BTN_TIMETABLE_COPY    32943
#define ID_RIBBON_BTN_TIMETABLE_PASTE   32944
#define ID_RIBBON_BTN_TIMETABLE_DEL     32945
#define ID_RIBBON_BTN_TIMETABLE_PREVIEWWINMODE 32946
#define ID_RIBBON_COMBOX_TIMETABLE_TIMEDELTA 32947
#define ID_RINBON_BTN_LAYOUT_NEW        32948
#define ID_RINBON_BTN_LAYOUT_DELETE     32949
#define ID_RINBON_BTN_LAYOUT_RENAME     32950
#define ID_RINBON_BTN_LAYOUT_EDIT       32951
#define ID_RINBON_BTN_LAYOUT_APPROVE    32952
#define ID_RINBON_BTN_LAYOUT_REJECT     32953
#define ID_RINBON_BTN_LAYOUT_REQUEST    32954
#define ID_RINBON_BTN_LAYOUT_PREVIEW    32955
#define ID_RINBON_BTN_LAYOUT_REFRESH    32956
#define ID_RINBON_BTN_LAYOUT_IMPORT     32957
#define ID_RIBBON_BTN_CLTMGMT_EDITGROUP 32961
#define ID_RIBBON_BTN_CLTMGMT_EDITCLT   32962
#define IDC_STATIC_TIMETABLE_APPROVE    32963
#define IDC_TIMETABLE_INFO_APPROVE      32964
#define ID_RIBBON_BTN_TIMETABLE_APPROVE 32965
#define ID_RIBBON_BTN_TIMETABLE_REJECT  32966
#define ID_RIBBON_BTN_TIMETABLE_REQUEST 32967
#define ID_RIBBON_BTN_TIMETABLE_EDIT    32968
#define ID_RIBBON_BTN_TIMETABLE_PUBLISH_ALL 32969
#define ID_RIBBON_BTN_TIMETABLE_DELTABLE 32970
#define ID_RIBBON_BTN_MEDIA_UPLOADURL   32971
#define ID_BTN_MEDIA_STARTUPLOAD        32972
#define ID_BTN_MEDIA_PAUSEUPLOAD        32973
#define ID_BTN_MEDIA_CANCELUPLOAD       32974
#define ID_BTN_MEDIA_STARTDOWNLOAD      32975
#define ID_BTN_MEDIA_PAUSEDOWNLOAD      32976
#define ID_BTN_MEDIA_CANCELDOWNLOAD     32977
#define ID_BTN_MEDIA_REFRESH            32978
#define ID_BTN_MEDIA_UPLOADED           32979
#define ID_BTN_MEDIA_UPLOADING          32980
#define ID_BTN_MEDIA_UPLOADFAILED       32981
#define ID_BTN_MEDIA_DOWNLOADED         32982
#define ID_BTN_MEDIA_DOWNLOADING        32983
#define ID_BTN_MEDIA_DOWNLOADFAILED     32984
#define ID_RIBBON_BTN_USRMGMT_REFRESH   32985
#define ID_RIBBON_BTN_TIMETABLE_RENAME  32986
#define ID_RIBBON_BTN_CLTMGMT_VOLUME    32987
#define ID_RIBBON_BTN_CLTMGMT_VIEWHISTORYCLT 32988
#define ID_RIBBON_COMBOX_PLAYER_SETTING 32989
#define ID_RIBBON_BTN_MEDIA_REFRESH     32990
#define ID_BTN_MEDIA_RESERVED           33000
#define ID_RIBBON_BTN_CLTMGMT_SEARCH    33001
#define IDS_SCHEDULE_COPY_RANGE         58100
#define IDS_SCHEDULE_COPY_WEEKDAYS      58101
#define ID_SCHEDULER_BASE               58200
#define ID_TIMETABLE_FILTER             60000
#define ID_TIMETABLE                    60001
#define ID_TIMETABLE_WND                60002
#define ID_TIMETABLE_SERACHED_LAYOUT_BAR 60003
#define ID_TIMETABLE_SERACHED_TIMETABLE_BAR 60004
#define ID_TIMETABLE_MANAGEMENT         60005
#define ID_TIMETABLE_EDIT               60006
#define ID_TIMETABLE_LAYOUT_FILTER      60007
#define ID_TIMETABLE_LAYOUT_INFO        60008
#define IDC_STATIC_GROUP_INFO           60009
#define IDC_STATIC_THUMBNAIL            60010
#define IDC_MEDIA_THUMBNAIL             60010
#define IDC_TIMETABLE_STARTTIME         60011
#define IDC_TIMETABLE_ENDTIME           60012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        488
#define _APS_NEXT_COMMAND_VALUE         33003
#define _APS_NEXT_CONTROL_VALUE         1429
#define _APS_NEXT_SYMED_VALUE           341
#endif
#endif
